### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by SeanKilleen** [lynnandtonic/oss-valentines#49]
Thought somebody might want to know! I always thought this was a cute thing on Valentine's day; sad to not see it there this year. But perhaps the time has come. 🥲 

![image](https://github.com/netlify/oss-valentines/assets/2148318/8e5cce89-cb98-445a-af82-cc5315442f87)

I suggest archiving this repo if it's no longer available (and thanks for it!)

**Comment by hexagoncircle** [comment]
Thanks for the heads up, @lynnandtonic! Surfacing this internally

**Comment by hexagoncircle** [comment]
The site can still be accessed at https://oss-valentine.netlify.app/ — unfortunately, logging in with GitHub won't work since it redirects you back to the primary domain. I've opened https://github.com/netlify/oss-valentines/pull/50 that switches strings in the codebase to the Netlify app domain, but I don't have repo settings access to change the auth callback url (assuming that it's handled somewhere in there). It may be best to archive this repo as recommended in the issue.

All that being said, this is personally still one of my favorite projects ❤️

**Comment by hexagoncircle** [comment]
@lynnandtonic—That sounds reasonable to me. I will bring it up and reach out to you directly on next steps

**Comment by lynnandtonic** [comment]
The site is back up and running! Thank you @SeanKilleen for filing this issue. 💚

**Comment by SeanKilleen** [comment]
@lynnandtonic wonderful news! 🎉❤️
